### ISSUE TITLE
issue number 1 issue number 1

### ISSUE THREAD

**Issue by tea-spoon** [tea-spoon/tea#1]
this is issue number 1... you can do what you want with it.

**Comment by block-spider** [comment]
@tea-spoon @testtip

**Comment by testtip** [comment]
@tea-spoon has [claimed](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld43pynuwhrr7r6zafkwvxhxuql0luxdn4hycs) the `0.0003 BCH`| `~   0.38 USD` sent by @block-spider via [chaintip](http://www.chaintip.org).

**Comment by block-spider** [comment]
@testtip 4 days

**Comment by testtip** [comment]
`0.0003 BCH`| `~   0.38 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld422cks3apv400k0nc7tf3pwwawjqq9jkjp2f) to this issue by @block-spider.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/7) by getting a pull request merged that fixes this issue.

**Comment by block-spider** [comment]
@testtip 1 days

**Comment by testtip** [comment]
Thank you @block-spider! `0.0006 BCH`| `~   0.75 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/7) by getting a pull request merged that fixes this issue.

**Comment by tea-spoon** [comment]
@testtip

**Comment by tea-spoon** [comment]
@block-spider @testtip

**Comment by testtip** [comment]
Thank you @tea-spoon! `0.0007 BCH`| `~   0.88 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/7) by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
@block-spider has [claimed](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld429zdaxjpeumhk0ujqs4hg0j87mcu05wvvxg) the `0.0004 BCH`| `~   0.50 USD` sent by @tea-spoon via [chaintip](http://www.chaintip.org).

**Comment by tea-spoon** [comment]
@testtip 5000 days

**Comment by testtip** [comment]
Thank you @tea-spoon! `0.0007 BCH`| `~   0.88 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/7) by getting a pull request merged that fixes this issue.
