### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by tea-spoon** [tea-spoon/tea#11]
test issue comment

**Comment by tea-spoon** [comment]
@testtip

**Comment by testtip** [comment]
`0.00067203 BCH`| `~   0.90 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld48df0trjnx5pxlasrmzr9t2s0y4q7rd0xsgr) to this issue by @tea-spoon.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/12) by getting a pull request merged that fixes this issue.

**Comment by block-spider** [comment]
@testtip

**Comment by testtip** [comment]
Thank you @block-spider! `0.00082084 BCH`| `~   1.10 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/12) by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
`0.00082084 BCH`| `~   1.10 USD` has now been claimed by @block-spider when pull request [#13](http://github.chaintip.org/tea-spoon/tea/pull/13) was merged.

**Comment by tea-spoon** [comment]
@testtip
