### ISSUE TITLE
asdf

### ISSUE THREAD

**Issue by tea-spoon** [tea-spoon/tea#14]
asdfasdf

**Comment by tea-spoon** [comment]
@testtip 1 day

**Comment by testtip** [comment]
`0.00014632 BCH`| `~   0.20 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld40phlzux9cr576zw99qgrk3lgf3c8dxqmr2a) to this issue by @tea-spoon.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/15) by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
`0.00014632 BCH`| `~   0.20 USD` has now been claimed by @block-spider when pull request [#16](http://github.chaintip.org/tea-spoon/tea/pull/16) was merged.
