### ISSUE TITLE
qwer

### ISSUE THREAD

**Issue by tea-spoon** [tea-spoon/tea#17]
qwerqwer

**Comment by tea-spoon** [comment]
qwer @testtip 4 days

**Comment by block-spider** [comment]
@testtip 2 days

**Comment by testtip** [comment]
`0.00014607 BCH`| `~   0.20 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld40d25e5zyshraq5xygr305yday4y0gqgaehs) to this issue by @tea-spoon.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/16) by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
Thank you @block-spider! `0.00029214 BCH`| `~   0.40 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/16) by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
`0.00029214 BCH`| `~   0.40 USD` has now been claimed by @block-spider when pull request [#18](http://github.chaintip.org/tea-spoon/tea/pull/18) was merged.
