### ISSUE TITLE
issue from blockspider

### ISSUE THREAD

**Issue by block-spider** [tea-spoon/tea#22]
hello

**Comment by block-spider** [comment]
@chaintip

**Comment by chaintip** [comment]
`0.00036534 BCH`| `~   0.50 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4z49qpnqptwex5yzf2jvrlg30h4qenxuhycs) to this issue by @block-spider.
Claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/1) by getting a pull request merged that fixes this issue.

**Comment by chaintip** [comment]
`0.00036534 BCH`| `~   0.50 USD` has now been claimed by @block-spider when pull request [#23](http://github.chaintip.org/tea-spoon/tea/pull/23) was merged.
