### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by tea-spoon** [tea-spoon/tea#3]
whatever

**Comment by block-spider** [comment]
@testtip 1 day

**Comment by testtip** [comment]
`0.003 BCH`| `~   3.85 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld42ncmet6cfyyq9yewy3uccejrf55e40av7zl) to this issue by @block-spider.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/8) by getting a pull request merged that fixes this issue.

**Comment by block-spider** [comment]
@testtip

**Comment by tea-spoon** [comment]
@testtip
