### ISSUE TITLE
hello issue

### ISSUE THREAD

**Issue by tea-spoon** [tea-spoon/tea#5]
hello issue body

**Comment by block-spider** [comment]
@testtip 5 days

**Comment by testtip** [comment]
`0.0003 BCH`| `~   0.40 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4gzedwta97xe4semq5muxn7e8dcswamcfmyq) to this issue by @block-spider.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/9) by getting a pull request merged that fixes this issue.
