### ISSUE TITLE
testing issue number 2

### ISSUE THREAD

**Issue by tea-spoon** [tea-spoon/tea#8]
asldkfjasldkjfalsdkjfa;slkdjfasldjf;alsdkjfasdfsda
asdfl;kajsdf;laksjdf

asdflkjasd;lfkjas;ldfkja;lsdkjfa;lsdkjf;alksdjf;alskdjf 

as;dlfkja;sdlkfj;asldkjfa;slkdjf;alsdkjf

**Comment by block-spider** [comment]
@testtip 0 days

**Comment by block-spider** [comment]
@testtip -1 days

**Comment by block-spider** [comment]
@testtip 0 days

**Comment by testtip** [comment]
`0.0003 BCH`| `~   0.40 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld489v66a76a9jktmdfh2z58hmgqtyw9u90q8r) to this issue by @block-spider.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/10) by getting a pull request merged that fixes this issue.

**Comment by block-spider** [comment]
@testtip 0 days

**Comment by testtip** [comment]
Thank you @block-spider! `0.0006 BCH`| `~   0.79 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/10) by getting a pull request merged that fixes this issue.

**Comment by tea-spoon** [comment]
@testtip 0 days

**Comment by testtip** [comment]
Thank you @tea-spoon! `0.0009 BCH`| `~   1.19 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/10) by getting a pull request merged that fixes this issue.

**Comment by tea-spoon** [comment]
@testtip 0 days

**Comment by testtip** [comment]
Thank you @tea-spoon! `0.0009 BCH`| `~   1.20 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/10) by getting a pull request merged that fixes this issue.
