### ISSUE TITLE
bug free issue (I wish)

### ISSUE THREAD

**Issue by tea-spoon** [tea-spoon/tea#9]
just another test (I'm dying here)

**Comment by tea-spoon** [comment]
@testtip

**Comment by testtip** [comment]
`0.0004 BCH`| `~   0.53 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4ydnlfjsjyzdn6a7p3s4gf57zy6vlzsamdh6) to this issue by @tea-spoon.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/11) by getting a pull request merged that fixes this issue.

**Comment by tea-spoon** [comment]
@block-spider @testtip

**Comment by block-spider** [comment]
@testtip 4 days

**Comment by testtip** [comment]
Thank you @block-spider! `0.0007 BCH`| `~   0.93 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/11) by getting a pull request merged that fixes this issue.

**Comment by block-spider** [comment]
@testtip 0 days

**Comment by testtip** [comment]
Thank you @block-spider! `0.0009 BCH`| `~   1.19 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/11) by getting a pull request merged that fixes this issue.

**Comment by block-spider** [comment]
@testtip 0 days

**Comment by testtip** [comment]
`0E-8 BCH`| `~   0.00 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/11) by getting a pull request merged that fixes this issue.

**Comment by tea-spoon** [comment]
@testtip 0 days

**Comment by tea-spoon** [comment]
@testtip 1 day

**Comment by testtip** [comment]
@testtip 0 days

**Comment by tea-spoon** [comment]
@testtip 0 days

**Comment by testtip** [comment]
Thank you @tea-spoon! `0.00066248 BCH`| `~   0.90 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/11) by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
`0.00029451 BCH`| `~   0.40 USD` has now been tipped to this issue.
Claim [this bounty](http://github.chaintip.org/testtip/bounties/issues/11) by getting a pull request merged that fixes this issue.

**Comment by testtip** [comment]
`0 BCH`| `~   0.00 USD` has now been claimed by @tea-spoon when pull request [#10](http://github.chaintip.org/tea-spoon/tea/pull/10) was merged.
